#!/bin/sh

# PROVIDE: wsdd
# REQUIRE: DAEMON samba_server
# BEFORE: login
# KEYWORD: shutdown

. /etc/rc.subr

name=wsdd
rcvar=wsdd_enable

wsdd_smb_config_file="/usr/local/etc/smb.conf"
if [ -r $wsdd_smb_config_file ]; then
	wsdd_group="$(grep -i '^[[:space:]]*workgroup[[:space:]]*=' $wsdd_smb_config_file | cut -f2 -d= | tr -d '[:blank:]')"
	wsdd_opts="-w ${wsdd_group}"
fi

command="/usr/sbin/daemon"
command_args="-u daemon -S /usr/local/bin/wsdd $wsdd_opts"

load_rc_config $name
run_rc_command "$1"
